config/routes.rb
Rails.application.routes.draw do
  get 'works/index'
  root 'works#index'
  delete 'works/delete'
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
	belongs_to :category
	belongs_to :user, optional: true
	scope :return_x_size, ->(x){ where(size: x)}
	scope :return_nil_users, ->{ where(user_id: nil)}
	after_destroy :category_delete

	def category_delete
		c = Category.all
		c.each do |elem|
			if elem.items.empty? 
				elem.destroy
			end
		end
	end
end

app/models/user.rb
class User < ApplicationRecord
	has_many :items, dependent: :destroy
	validates :name, presence: true
	validates :email, uniqueness: true

	before_save :capitalize_name

	def capitalize_name
		self.name.capitalize!
	end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  def index
  	@i = Item.all
  end

  # def delete
  # 	Item.find_by(id:elem).destroy
  # end

  def delete
  	@item = Item.find(params[:id])
  	@item.destroy
  	redirect_to :action => 'index'
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Prueba2Sebastianquevedo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/works/index.html.erb
<h1>Works#index</h1>
<p>Find me in app/views/works/index.html.erb</p>


<table>
	<tr>
		<td>Item serial</td>
		<td>Category</td>
		<td>User</td>
	</tr>
	<% @i.each do |elem| %>
		<tr>
			<td><%= elem.serialnumber %></td>
			<td><%= elem.category.name %></td>
			<td><%= elem.user %></td>
			<td><%= link_to 'Destroy', works_delete_path(id: elem.id),
                    method: :delete, data: { confirm: 'Are you sure?' } %></td>
		</tr>
	<% end %>
</table>